
project_id = "rsbzrlvezpcejzyvkmpx"

[functions.twitter-request-token]
verify_jwt = false

[functions.twitter-access-token]
verify_jwt = false

[functions.twitter-post]
verify_jwt = false

[functions.twitter-analytics]
verify_jwt = false

[functions.debug-x-connection]
verify_jwt = false

[functions.ayrshare-post]
verify_jwt = false
