// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsbzrlvezpcejzyvkmpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzYnpybHZlenBjZWp6eXZrbXB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExOTIyNTEsImV4cCI6MjA1Njc2ODI1MX0.Fq7vbTg5f4Gq4xKhPadQqydMYrSiQqOZQdCfwlOTs2Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);